site_name: LoRa Communicater Docs
theme:
    name: material
    custom_dir: 'theme'
    language: 'ja'
    palette:
      primary: 'purple'
      accent: 'black'
extra:
    search:
        language: 'jp'
markdown_extensions:
  - fontawesome_markdown
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
extra_css:
  - "https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css"  
  - 'stylesheets/extra.css'
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/styles/default.min.css
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/highlight.min.js
  - javascripts/config.js
plugins:
  - macros
nav:
  - Home: "index.md"
  - 開発環境: "dev.md"
  - 回路図: "schematic.md"
  - LoRaモジュール: "lora.md"
  - 設定値: "param.md"